import Head from "next/head";

import { fetchHeroes } from "../utils/fetch";
import { useState } from "react";

import { MD5 } from "crypto-js";
import Image from "next/image";
import Link from "next/link";
import Env from "../utils/env";

export const getStaticProps = async () => {
  const apiUrl = process.env.BASE_URL;
  const apiKey = process.env.API_KEY;
  const privateKey = process.env.PRIVATE_API_KEY;

  let url = await fetchHeroes(
    "/v1/public/characters",
    apiUrl,
    apiKey,
    privateKey
  );

  let res = await fetch(url);

  let heroes = await res.json();

  return {
    props: {
      heroes,
    },

    revalidate: 86400,
  };
};

export default function Home({ heroes }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container pt-24 mx-auto">
        {console.log(heroes.data.results)}
        <div className="grid grid-cols-6 gap-5">
          {heroes.data.results.map((hero) => (
            <Link href={`characters/${hero.id}`} key={hero.id}>
              <div className="shadow bg-white p-3 cursor-pointer">
                <div className="w-full h-64 relative">
                  <Image
                    alt={hero.name}
                    src={`${hero.thumbnail.path}.${hero.thumbnail.extension}`}
                    layout="fill"
                    className="object-top object-cover w-10"
                  />
                </div>
                <h1 className="text-xl uppercase font-robotoCondensed font-bold text-center">
                  {hero.name}
                </h1>
              </div>
            </Link>
          ))}
        </div>
      </main>
    </div>
  );
}
