import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container h-screen pt-48 mx-auto">
        <div className="justify-center text-center">
          <h1 className="text-3xl">Welcome to Marvel Traverse</h1>
          <h3>Page is still under development</h3>
        </div>
      </div>
    </div>
  );
}
